version: '3.8'

services:
  frontend:
    container_name: frontend-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

# to make it visible on inspection
volumes: 
  app:
  node_modules: