version: '3.8'

services:
  medbox-frontend_server:
    container_name: medbox-frontend_server
    image: medbox-frontend_server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

# to make it visible on inspection
volumes: 
  app:
  node_modules: