version: '3.8'

services:
    # config for the primary database
    mainDB:
        image: postgres
        environment:
            - POSTGRES_DB=mainDB
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

        volumes:
            - ./_dbData/mainDB:/var/lib/postgresql/data

    # config for building a web image
    web:
        build: ./src
        image: webserver
        command: python manage.py runserver 0.0.0.0:8000
        container_name: webapp-server

        depends_on:
            - mainDB
                
        ports:
            - "8000:8000"
