version: '3.8'

services:
    medbox-datasbase_server:
        image: postgres:13.2
        container_name: medbox-database_server_prod
        environment:
            - POSTGRES_DB=mainDB
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - /home/github/postgres-data:/var/lib/postgresql/data

    medbox-backend_server:    
        image: eu.gcr.io/flowing-access-311114/medbox_backend-server:${GITHUB_RUN_ID}
        container_name: medbox-backend_server_prod
        environment: 
            - DEBUG=on
            - SECRET_KEY=${SECRET_KEY}
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - DB_NAME=mainDB
            - DB_HOST=medbox-database_server_prod
            - DB_PORT=5432
            - DJANGO_SUPERUSER_EMAIL=superemail@gmail.com
            - DJANGO_SUPERUSER_PASSWORD=superpassword
        command: python manage.py runserver 0.0.0.0:8000
        depends_on:
            - medbox-database_server_prod
        ports:
            - "8000:8000"
            
    medbox-frontend_server:
        image: eu.gcr.io/flowing-access-311114/medbox_frontend-server:${GITHUB_RUN_ID}
        container_name: medbox-frontend_server_prod
        depends_on:
            - medbox-backend_server_prod
    
        ports:
            - 80:80