version: '3.8'

services:
    # config for database container
    medbox-datasbase_server:
        image: postgres
        container_name: medbox-database_server
        environment:
            - POSTGRES_DB=mainDB
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

        volumes:
            - ./_dbData/mainDB:/var/lib/postgresql/data

    # config for backend container
    medbox-backend_server:
        build: ./backend
        image: medbox-backend_server
        command: python manage.py runserver 0.0.0.0:8000
        container_name: medbox-backend_server
        volumes:
            - ./backend/app/:/usr/src/app/
        depends_on:
            - medbox-datasbase_server
        ports:
            - "8000:8000"
        env_file: 
            - ./backend/app/.env.dev

# to make it visible on inspection
volumes:
    mainDB:
    app: