version: '3.8'

services:
    medbox-datasbase_server:
        image: postgres
        container_name: medbox-database_server_prod

        environment:
            - POSTGRES_DB=mainDB
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

        volumes:
            - ./_dbData/mainDB:/var/lib/postgresql/data

    medbox-backend_server:
        build:
            context: .
            dockerfile: Dockerfile.prod
        
        image: medbox-backend_server_prod
        container_name: medbox-backend_server_prod
        command: python manage.py runserver 0.0.0.0:8000
        
        volumes:
            - ./backend/app/:/usr/src/app/
        
        depends_on:
            - medbox-datasbase_server
        
        ports:
            - "8000:8000"
        
        env_file: 
            - ./backend/app/.env.dev

    medbox-frontend_server:
        build:
            context: .
            dockerfile: Dockerfile.prod
        
        image: medbox-frontend_server_prod
        container_name: medbox-frontend_server_prod

        volumes:
            - './frontend/:/app'
            - '/app/node_modules'
        
        depends_on:
            - medbox-backend_server
    
        ports:
            - 80:80