version: '3.8'

services:
    # config for database container
    mainDB:
        image: postgres
        environment:
            - POSTGRES_DB=mainDB
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

        volumes:
            - ./_dbData/mainDB:/var/lib/postgresql/data

    # config for backend container
    backend:
        build: ./backend
        image: backend-server
        command: python manage.py runserver 0.0.0.0:8000
        container_name: backend-server
        volumes:
            - ./backend/app/:/usr/src/app/
        depends_on:
            - mainDB
        ports:
            - "8000:8000"
        env_file: 
            - ./backend/app/.env.dev

# to make it visible on inspection
volumes:
    mainDB:
    app: