version: '3.8'

services:
    medbox-database_server:
        image: postgres
        container_name: medbox-database_server

        environment:
            - POSTGRES_DB=mainDB
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

        volumes:
            - ./_dbData/mainDB:/var/lib/postgresql/data

    medbox-backend_server:
        build: ./backend
        image: medbox-backend_server
        container_name: medbox-backend_server
        command: python manage.py runserver 0.0.0.0:8000
        
        volumes:
            - ./backend/app/:/usr/src/app/
        
        depends_on:
            - medbox-datasbase_server
        
        ports:
            - "8000:8000"
        
        env_file: 
            - ./backend/app/.env.dev

    medbox-frontend_server:
        build: ./frontend
        image: medbox-frontend_server
        container_name: medbox-frontend_server

        volumes:
            - './frontend/:/app'
            - '/app/node_modules'
        
        depends_on:
            - medbox-backend_server
    
        ports:
            - 3000:3000
        
        environment:
            - CHOKIDAR_USEPOLLING=true
        
        stdin_open: true
        tty: true
