# Generated by Django 3.0 on 2020-11-20 13:43

import AppAPI.models.dose
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DeviceAPI', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('producer', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('associated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PredefinedTime',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('time', models.TimeField()),
                ('name', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predefinedTimes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dose',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('planned_administration_time', models.DateTimeField(blank=True, null=True, validators=[AppAPI.models.dose.planned_administration_time_validator])),
                ('number_of_pills', models.FloatField(validators=[AppAPI.models.dose.number_of_pills_validator])),
                ('on_demand', models.BooleanField(default=False)),
                ('chamber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doses', to='DeviceAPI.Chamber')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doses', to='AppAPI.Medicine')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doses', to='AppAPI.Treatment')),
            ],
        ),
    ]
