# Generated by Django 3.0 on 2020-09-05 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAPI', '0002_auto_20200904_1239'),
        ('AppAPI', '0002_auto_20200904_1446'),
    ]

    operations = [
    ]
