# Generated by Django 3.0 on 2020-08-28 10:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('AppAPI', '0002_auto_20200828_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dose',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('plannedAdministrationTime', models.DateTimeField()),
                ('numberOfPills', models.FloatField()),
                ('onDemand', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='medicinedosing',
            name='adherenceTimes',
        ),
        migrations.RemoveField(
            model_name='medicinedosing',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='treatmenttoken',
            name='treatment',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='caretaker',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='maxDeviation',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='medicines',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='patientFirstName',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='patientLastName',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='predefinedTimes',
        ),
        migrations.AddField(
            model_name='treatment',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='treatment',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='AdherenceTime',
        ),
        migrations.DeleteModel(
            name='MedicineDosing',
        ),
        migrations.DeleteModel(
            name='TreatmentToken',
        ),
        migrations.AddField(
            model_name='dose',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppAPI.Medicine'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='doses',
            field=models.ManyToManyField(to='AppAPI.Dose'),
        ),
    ]
