# Generated by Django 3.0 on 2020-08-28 11:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('AppAPI', '0003_auto_20200828_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedTime',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
