# Generated by Django 3.0 on 2020-09-05 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAPI', '0004_auto_20200905_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatment',
            old_name='patient',
            new_name='associatedUser',
        ),
    ]
