# Generated by Django 2.2.12 on 2020-05-24 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_treatment_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=16, unique=True)),
                ('expires', models.DateTimeField()),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Website.Treatment')),
            ],
        ),
    ]
