# Generated by Django 3.0 on 2020-11-13 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('capacity', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('pairing_code', models.CharField(default='', max_length=6)),
                ('pairing_code_expires_at', models.DateTimeField(null=True)),
                ('api_token', models.CharField(blank=True, default='', max_length=42)),
                ('serial_number', models.UUIDField(blank=True, null=True)),
                ('hardware_version', models.CharField(blank=True, default='', max_length=11)),
                ('firmware_version', models.CharField(blank=True, default='', max_length=11)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownedDevices', to=settings.AUTH_USER_MODEL)),
                ('supervisors', models.ManyToManyField(related_name='supervisedDevices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TelemetryLog',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.PositiveIntegerField()),
                ('signal_strength', models.PositiveSmallIntegerField()),
                ('battery_status', models.PositiveSmallIntegerField()),
                ('battery_voltage', models.PositiveSmallIntegerField()),
                ('device_status', models.PositiveSmallIntegerField(choices=[(0, 'Ok'), (1, 'Unexpected Error'), (2, 'Battery Low')])),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_logs', to='DeviceAPI.Device')),
            ],
        ),
        migrations.CreateModel(
            name='DebugLog',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('severity', models.PositiveSmallIntegerField(choices=[(0, 'Info'), (1, 'Warning'), (2, 'Critical')])),
                ('timestamp', models.PositiveIntegerField()),
                ('message_code', models.PositiveSmallIntegerField(choices=[(0, 'Device On'), (1, 'Container In'), (2, 'Container Out'), (3, 'Button Pressed')])),
                ('details', models.CharField(blank=True, default='', max_length=256)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debug_logs', to='DeviceAPI.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('capacity', models.PositiveSmallIntegerField()),
                ('position', models.PositiveSmallIntegerField()),
                ('last_refill', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='DeviceAPI.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Chamber',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('position', models.PositiveSmallIntegerField()),
                ('is_full', models.BooleanField(default=False)),
                ('real_administration_time', models.DateTimeField(blank=True, null=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambers', to='DeviceAPI.Container')),
            ],
        ),
    ]
