# Generated by Django 3.0 on 2020-08-28 11:38

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('AppAPI', '0004_predefinedtime'),
        ('DeviceAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamber',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('position', models.PositiveSmallIntegerField()),
                ('isFull', models.BooleanField(default=True)),
                ('realAdministrationTime', models.DateTimeField(null=True)),
                ('doses', models.ManyToManyField(to='AppAPI.Dose')),
            ],
        ),
        migrations.RemoveField(
            model_name='device',
            name='serialNumber',
        ),
        migrations.AddField(
            model_name='device',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('position', models.PositiveSmallIntegerField()),
                ('lastRefill', models.DateTimeField(default=django.utils.timezone.now)),
                ('chambers', models.ManyToManyField(to='DeviceAPI.Chamber')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='containers',
            field=models.ManyToManyField(to='DeviceAPI.Container'),
        ),
    ]
