# Generated by Django 3.0 on 2020-11-15 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='api_token',
        ),
        migrations.AddField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this device should be treated as active. Unselect this instead of deleting device object.', verbose_name='active'),
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_token', to='DeviceAPI.Device', verbose_name='Device')),
            ],
            options={
                'verbose_name': 'DeviceToken',
                'verbose_name_plural': 'DeviceTokens',
                'abstract': False,
            },
        ),
    ]
