# Generated by Django 3.0 on 2020-09-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='version',
        ),
        migrations.RemoveField(
            model_name='device',
            name='version',
        ),
        migrations.AddField(
            model_name='container',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='ContainerVersion',
        ),
        migrations.DeleteModel(
            name='DeviceVersion',
        ),
    ]
