# Generated by Django 3.0 on 2020-08-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAPI', '0004_predefinedtime'),
        ('DeviceAPI', '0002_auto_20200828_1138'),
        ('AdminPanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='devices',
            field=models.ManyToManyField(to='DeviceAPI.Device'),
        ),
        migrations.AddField(
            model_name='user',
            name='predefinedTimes',
            field=models.ManyToManyField(to='AppAPI.PredefinedTime'),
        ),
        migrations.AddField(
            model_name='user',
            name='treatments',
            field=models.ManyToManyField(to='AppAPI.Treatment'),
        ),
    ]
