# Generated by Django 3.0 on 2020-09-04 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0002_auto_20200901_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
