name: Build and Deploy

on: workflow_dispatch

jobs:
  Deploy:
    runs-on: self-hosted
    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DOCKER_AUTH: ${{ secrets.DOCKER_AUTH }}
    steps:
    - uses: actions/checkout@v2
    - name: Substitute envs
      run: |
        envsubst -v < "docker-compose.prod.yml" > docker-compose.final.yml
    - name: Authenticate
      run: |
        echo ${DOCKER_AUTH} | base64 -d | docker login -u _json_key --password-stdin https://eu.gcr.io
    - name: test 
      run: |
        cat docker-compose.final.yml
        docker-compose -f docker-compose.final.yml up
