name: Django Tests

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches-ignore:
      - master

jobs:
  Test:
    runs-on: ubuntu-20.04
    env:
      SECRET_KEY: hoktr^5edgngixl%2o6_n)e8smv$7g73+geiwk01!v5veg^z&l
      WORKDIR: ./backend
      DEBUG: on

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ${{env.WORKDIR}}
    - name: Run Tests
      run: |
        python manage.py test
      working-directory: ${{env.WORKDIR}}/app

  Build:
    runs-on: ubuntu-20.04
    needs: Test
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d

  
